services:
  mysql-db:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306 # For Linux use 3306:3306/tcp
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<Enter a root user password>
      - MYSQL_DATABASE=<Enter a database name>
    
volumes:
  db: